package assignment.tutoring;

public enum FilterCriteriaType {
    OVERALL_GRADE_SUPERIOR_TO,
    OVERALL_GRADE_INFERIOR_TO,
    NB_ABSENCES_SUPERIOR_TO,
    NB_ABSENCES_INFERIOR_TO,
    RESSOURCE_OVERALL_GRADE_SUPERIOR_TO,
    RESSOURCE_OVERALL_GRADE_INFERIOR_TO,
}
